// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parentaliza.Infrastructure.Context;

#nullable disable

namespace Parentaliza.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124232746_ParentalizaDbContext")]
    partial class ParentalizaDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Parentaliza.Domain.Entidades.BebeGestacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ComprimentoEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("date");

                    b.Property<int>("DiasDeGestacao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PesoEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("BebeGestacao", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.BebeNascido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<int>("IdadeMeses")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("TipoSanguineo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("BebeNascido", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.Conteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Conteudos", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ControleFralda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BebeNascidoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraTroca")
                        .HasColumnType("datetime");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TipoFralda")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BebeNascidoId");

                    b.ToTable("ControlesFralda", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ControleLeiteMaterno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BebeNascidoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Cronometro")
                        .HasColumnType("datetime");

                    b.Property<string>("LadoDireito")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LadoEsquerdo")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BebeNascidoId");

                    b.ToTable("ControlesLeiteMaterno", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ControleMamadeira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Anotacao")
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("BebeNascidoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<decimal?>("QuantidadeLeite")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BebeNascidoId");

                    b.ToTable("ControlesMamadeira", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.EventoAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Anotacao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("EventoAgenda", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ExameRealizado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BebeNascidoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRealizacao")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ExameSusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(500)");

                    b.Property<ulong>("Realizado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ExameSusId");

                    b.HasIndex("BebeNascidoId", "ExameSusId")
                        .IsUnique();

                    b.ToTable("ExamesRealizados", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ExameSus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoriaFaixaEtaria")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("IdadeMaxMesesExame")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMinMesesExame")
                        .HasColumnType("int");

                    b.Property<string>("NomeExame")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ExameSus", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.Responsavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FaseNascimento")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<int>("TipoResponsavel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.VacinaAplicada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<ulong>("Aplicada")
                        .HasColumnType("bit");

                    b.Property<Guid>("BebeNascidoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataAplicacao")
                        .HasColumnType("datetime");

                    b.Property<string>("LocalAplicacao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lote")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("VacinaSusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VacinaSusId");

                    b.HasIndex("BebeNascidoId", "VacinaSusId")
                        .IsUnique();

                    b.ToTable("VacinasAplicadas", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.VacinaSus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoriaFaixaEtaria")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("IdadeMaxMesesVacina")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMinMesesVacina")
                        .HasColumnType("int");

                    b.Property<string>("NomeVacina")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("VacinaSus", (string)null);
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.BebeGestacao", b =>
                {
                    b.HasOne("Parentaliza.Domain.Entidades.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.BebeNascido", b =>
                {
                    b.HasOne("Parentaliza.Domain.Entidades.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ControleFralda", b =>
                {
                    b.HasOne("Parentaliza.Domain.Entidades.BebeNascido", "BebeNascido")
                        .WithMany()
                        .HasForeignKey("BebeNascidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BebeNascido");
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ControleLeiteMaterno", b =>
                {
                    b.HasOne("Parentaliza.Domain.Entidades.BebeNascido", "BebeNascido")
                        .WithMany()
                        .HasForeignKey("BebeNascidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BebeNascido");
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ControleMamadeira", b =>
                {
                    b.HasOne("Parentaliza.Domain.Entidades.BebeNascido", "BebeNascido")
                        .WithMany()
                        .HasForeignKey("BebeNascidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BebeNascido");
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.EventoAgenda", b =>
                {
                    b.HasOne("Parentaliza.Domain.Entidades.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.ExameRealizado", b =>
                {
                    b.HasOne("Parentaliza.Domain.Entidades.BebeNascido", "BebeNascido")
                        .WithMany()
                        .HasForeignKey("BebeNascidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parentaliza.Domain.Entidades.ExameSus", "ExameSus")
                        .WithMany()
                        .HasForeignKey("ExameSusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BebeNascido");

                    b.Navigation("ExameSus");
                });

            modelBuilder.Entity("Parentaliza.Domain.Entidades.VacinaAplicada", b =>
                {
                    b.HasOne("Parentaliza.Domain.Entidades.BebeNascido", "BebeNascido")
                        .WithMany()
                        .HasForeignKey("BebeNascidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parentaliza.Domain.Entidades.VacinaSus", "VacinaSus")
                        .WithMany()
                        .HasForeignKey("VacinaSusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BebeNascido");

                    b.Navigation("VacinaSus");
                });
#pragma warning restore 612, 618
        }
    }
}
